# Manual similar sounding words
exitVoice = {"exit voice"}
endTurn = {"end turn", "and turn", "entertain", "nth term", "anton", "enstone", "and 10", "enter", "end term"}
singlePlayer = {"single player"}
difficulty = {"difficulty"}
normal = {"normal"}
expert = {"expert"}
deck = {"deck", "dick", "next", "text", "tech", "ek", "jet"}
opponent = {"opponent", "appointment", "exponent"}
start = {"start"}
game = {"game", "again"}
attack = {"attack", "a tack", "tech"}
mulligan = {"mulligan", "milligan"}
allFace = {"all face", "altace", "old face"}
target = {"target"}
confirm = {"confirm"}
heroPower = {"hero power"}
choose = {"choose", "cheese"}
hide = {"hide"}
show = {"show"}
cancel = {"cancel"}
hand = {"hand", "and"}
allSet = {"all", "lol", "tool"}
board = {"board", "bored", "old"}

zero = {"zero", "0"}
one = {"one", "1"}
two = {"two", "2", "too", "to"}
three = {"three", "3", "free"}
four = {"four", "4", "for"}
five = {"five", "5"}
six = {"six", "6"}
seven = {"seven", "7"}
eight = {"eight", "8", "ate"}
nine = {"nine", "9"}
ten = {"ten", "10"}

dec1= {"dec1", "daquan"}
dec2= {"dec2", "bectu"}
dec3= {"dec3", "dec free"}
dec4= {"dec4"}
dec5= {"dec5"}
dec6= {"dec6"}
dec7= {"dec7"}
dec8= {"dec8","decade"}
dec9= {"dec9"}

playCardTwo = {"play cartoon"}
chooseThree = {"shrewsbury"}
handAll = {"handle"}